In [5]:
import numpy as np

# Q1
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a
print("Corrected:", temperature + 2)

# b
print("Fahrenheit:", temperature * 9 / 5 + 32)

# c
print("Readings > 32:", temperature[temperature > 32])

# d
print("Count > 32:", np.sum(temperature > 32))

# e
print("Vectorization and Boolean indexing apply operations to the whole array at once in compiled C code, so they are faster and need less code than a Python for loop.")

Corrected: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Readings > 32: [35 38 33 40]
Count > 32: 4
Vectorization and Boolean indexing apply operations to the whole array at once in compiled C code, so they are faster and need less code than a Python for loop.


In [6]:
# Q2
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]])

# a
print("Total steps:", steps.sum())

# b
print("Mean steps:", steps.mean())

# c
print("Max:", steps.max())
print("Min:", steps.min())

# d
print("Total per day:", steps.sum(axis=0))

# e
print("Total per user:", steps.sum(axis=1))

# f
pos = np.unravel_index(steps.argmax(), steps.shape)
print("Position of max (user, day):", pos)

Total steps: 84200
Mean steps: 7016.666666666667
Max: 9500
Min: 4500
Total per day: [26500 27300 30400]
Total per user: [18300 24500 14400 27000]
Position of max (user, day): (3, 2)


In [7]:
# Q3
# a
original = np.array([1, 2, 3, 4, 5, 6])

# b
subset = original[1:4]

# c
subset[0] = 999
print("original:", original)
print("subset:", subset)

# d
copied = original[1:4].copy()
copied[0] = 500
print("original:", original)
print("copied:", copied)

# e
m = np.arange(1, 13).reshape(3, 4)
print(m)

# f
print("First row:", m[0])
print("Last row:", m[-1])
print("Second column:", m[:, 1])
print("Rows 1-2, cols 2-3:\n", m[0:2, 1:3])

# g
f = m.flatten()
r = m.ravel()
print("flatten:", f)
print("ravel:", r)

# h
r[0] = 100
print("After changing ravel:\n", m)
print("Original affected, ravel returns a view")

# i
f[1] = 200
print("After changing flatten:\n", m)
print("Original not affected, flatten returns a copy")

# j
print("Shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)

original: [  1 999   3   4   5   6]
subset: [999   3   4]
original: [  1 999   3   4   5   6]
copied: [500   3   4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, cols 2-3:
 [[2 3]
 [6 7]]
flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After changing ravel:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Original affected, ravel returns a view
After changing flatten:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Original not affected, flatten returns a copy
Shape: (3, 4)
ndim: 2
size: 12
dtype: int32


In [4]:
# Q4
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]])
y = np.array([40, 65, 30, 85])

print(X.shape, X.ndim)
print(X.T)
# b) Transpose swaps rows and columns: each row now holds one feature across all users.
print(X.T @ X)
print(np.linalg.inv(X.T @ X))

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print(beta)
# f) Each coefficient is the change in assistance score per unit increase in that feature (sleep, activity, stress), holding the others fixed.

new_user = np.array([5, 40, 7])
print(new_user @ beta)

(4, 3) 2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]
75.27862544779009
