In [2]:
import numpy as np
# Q1
a = np.array([0,1,2,3,4])
print("Original array ", a)
# a
print("Add 2 ", a + 2)
# b
print("Mul by 3 ", a * 3)
# c
print("Div by 2 ", a / 2)

Original array  [0 1 2 3 4]
Add 2  [2 3 4 5 6]
Mul by 3  [ 0  3  6  9 12]
Div by 2  [0.  0.5 1.  1.5 2. ]


In [3]:
# Q2 
# a
arr = np.array([1, 2, 3, 6, 4, 5])
r = np.flip(arr)
print("Revered arr : ", r)
# b
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
# i
mfreq =  np.bincount(x).argmax() 
ind = np.where(x == mfreq)[0]
print("Most freq value = ", mfreq, " and index = ", ind)

# ii 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
mfreq2 =  np.bincount(y).argmax() 
ind2 = np.where(y == mfreq2)[0]
print("Most freq value = ", mfreq2, " and index = ", ind2)

Revered arr :  [5 4 6 3 2 1]
Most freq value =  1  and index =  [0 5 7 8 9]
Most freq value =  1  and index =  [0 1 2]


In [4]:
# Q3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# a
print(arr[0,1])
# b
print(arr[2,0])

20
70


In [5]:
# Q4
Kiran = np.linspace(10, 100, 25)
print(Kiran.ndim)
print(Kiran.shape)
print(Kiran.size)
print(Kiran.dtype)
print(Kiran.nbytes)

t = Kiran.reshape(25, 1)
print(t)
print(Kiran.T)  # no change for 1-D array

1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
# Q5
ucs420_kiran = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]).reshape(3, 4)
print(ucs420_kiran.mean())
print(np.median(ucs420_kiran))
print(ucs420_kiran.max())
print(ucs420_kiran.min())
print(np.unique(ucs420_kiran))

reshaped_ucs420_kiran = ucs420_kiran.reshape(4, 3)
print(reshaped_ucs420_kiran)

resized_ucs420_kiran = np.resize(ucs420_kiran, (2, 3))
print(resized_ucs420_kiran)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
